### ISSUE TITLE
Error opening board.

### ISSUE THREAD

**Issue by juvinski** [mirkix/BBBMINI-PCB#2]
Hi,

I was trying to open the PBC on KiCad(build 4029 25 October 2014) on linux(Ubuntu 15.10)and receiving error:
Error loading board.
PARSE_ERROR: Unexpected 'grid_origin' in input/source "/home/juvinski/Projetos/BBBMINI-PCB/kicad/bbbmini/bbbmini.kicad_pcb", line 74, offset 6
from /build/buildd/kicad-0.20141025+bzr4029/common/dsnlexer.cpp : Unexpected() : line 317

Anyone has some clue?

Thanks

**Comment by earsneyes** [comment]
@juvinski looks like you need to update your KiCad installation. Had problems opening the file as well until i upgraded KiCad.
Cheers!

**Comment by juvinski** [comment]
Hi @earsneyes,

thanks for the clue. I found on Kicad website a note about it, regular Ubuntu repository use an outdated version.
Following this steps
https://code.launchpad.net/~js-reynaud/+archive/ubuntu/ppa-kicad
I could update kicad and open the diagrams 

Thanks.

Regards
