### ISSUE TITLE
SR04-ECHO pin level for the range finder

### ISSUE THREAD

**Issue by pierre-quelin** [mirkix/BBBMINI-PCB#6]
Hello,
I'm not a specialist in electronic but I think there is a level problem with the SR04-ECHO input.
I think that the right schematic is a voltage divider circuit :

Echo(p19 pin3)
R2(1k)
SR04_ECHO (p8 pin15) **3.3V !!!**
R3(2k)
GND (p19 pin4)

Thank you very much for your job !

**Comment by mirkix** [comment]
@pierre-quelin 
Thanks! You are right (it is p8 pin16), will fix it in Rev 1.5.
