### ISSUE TITLE
In the schematic both MPU9250 MS6511 are marked as using the same SPI1 bus

### ISSUE THREAD

**Issue by ashwinvasudevan** [mirkix/BBBMINI-PCB#8]
At, https://github.com/mirkix/BBBMINI-PCB/blob/master/schematic/bbbmini.pdf
MS6511 and MPU9250, are both marked to use SPI1Bus. One of them should point to SPI0.

**Comment by mirkix** [comment]
@ashwinvasudevan Both use SPI1 chip select is done via CS lines. SPI0 can be used by a second MPU-9250.
